---

- name: copy of the manifests kubernetes to the master node 
  hosts: k8s_masters
  tasks: 
  - name: copy docker composer file to node
    copy: 
      src: ../kubernetes/
      dest: ~/kubernetes/
    #become: yes

  - name: deploy the database
    command: "kubectl apply -f ~/kubernetes/database.yml"

  - name: deploy the backend app
    command: "kubectl apply -f ~/kubernetes/backend.yml"

  - name: deploy the frontend app
    command: "kubectl apply -f ~/kubernetes/frontend.yml"
